Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.synced_folder "../../..", "/usr/src/proot", type: "sshfs"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
    vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y clang \
                        clang-tools-4.0 \
                        curl \
                        gcc \
                        gdb \
                        git \
                        lcov \
                        libarchive-dev \
                        libtalloc-dev \
                        make \
                        sloccount \
                        strace \
                        swig \
                        uthash-dev
  SHELL

end
