/* This file was generated thanks to the following command:
 *
 *     grep '^case PR_' enter.c exit.c host_path.c | cut -f 2 -d ' ' | cut -f 1 -d : | sort -u
 */

{ PR_chmod,		0 },
{ PR_chown,		0 },
{ PR_chown32,		0 },
{ PR_chroot,		0 },
{ PR_fchmod,		0 },
{ PR_fchmodat,		0 },
{ PR_fchown,		0 },
{ PR_fchown32,		0 },
{ PR_fchownat,		0 },
{ PR_fchownat,		0 },
{ PR_fstat,		0 },
{ PR_fstat,		0 },
{ PR_fstat64,		0 },
{ PR_fstatat64,		0 },
{ PR_getegid,		0 },
{ PR_getegid32,		0 },
{ PR_geteuid,		0 },
{ PR_geteuid32,		0 },
{ PR_getgid,		0 },
{ PR_getgid32,		0 },
{ PR_getresgid,		0 },
{ PR_getresgid32,	0 },
{ PR_getresuid,		0 },
{ PR_getresuid32,	0 },
{ PR_getuid,		0 },
{ PR_getuid32,		0 },
{ PR_lchown,		0 },
{ PR_lchown32,		0 },
{ PR_lstat,		0 },
{ PR_lstat64,		0 },
{ PR_mknod,		0 },
{ PR_newfstatat,	0 },
{ PR_oldlstat,		0 },
{ PR_oldstat,		0 },
{ PR_setfsgid,		0 },
{ PR_setfsgid32,	0 },
{ PR_setfsuid,		0 },
{ PR_setfsuid32,	0 },
{ PR_setgid,		0 },
{ PR_setgid32,		0 },
{ PR_setresgid,		0 },
{ PR_setresgid32,	0 },
{ PR_setresuid,		0 },
{ PR_setresuid32,	0 },
{ PR_setuid,		0 },
{ PR_setuid32,		0 },
{ PR_stat,		0 },
{ PR_stat64,		0 },
{ PR_statfs,		0 },
{ PR_statfs64,		0 },
