/* This file was generated thanks to the following command:
 *
 *     grep '^case PR_' enter.c exit.c host_path.c | cut -f 2 -d ' ' | cut -f 1 -d : | sort -u
 */

{ PR_chmod,		FILTER_SYSEXIT },
{ PR_chown,		FILTER_SYSEXIT },
{ PR_chown32,		FILTER_SYSEXIT },
{ PR_chroot,		FILTER_SYSEXIT },
{ PR_fchmod,		FILTER_SYSEXIT },
{ PR_fchmodat,		FILTER_SYSEXIT },
{ PR_fchown,		FILTER_SYSEXIT },
{ PR_fchown32,		FILTER_SYSEXIT },
{ PR_fchownat,		FILTER_SYSEXIT },
{ PR_fchownat,		FILTER_SYSEXIT },
{ PR_fstat,		FILTER_SYSEXIT },
{ PR_fstat,		FILTER_SYSEXIT },
{ PR_fstat64,		FILTER_SYSEXIT },
{ PR_fstatat64,		FILTER_SYSEXIT },
{ PR_getegid,		FILTER_SYSEXIT },
{ PR_getegid32,		FILTER_SYSEXIT },
{ PR_geteuid,		FILTER_SYSEXIT },
{ PR_geteuid32,		FILTER_SYSEXIT },
{ PR_getgid,		FILTER_SYSEXIT },
{ PR_getgid32,		FILTER_SYSEXIT },
{ PR_getresgid,		FILTER_SYSEXIT },
{ PR_getresgid32,	FILTER_SYSEXIT },
{ PR_getresuid,		FILTER_SYSEXIT },
{ PR_getresuid32,	FILTER_SYSEXIT },
{ PR_getuid,		FILTER_SYSEXIT },
{ PR_getuid32,		FILTER_SYSEXIT },
{ PR_lchown,		FILTER_SYSEXIT },
{ PR_lchown32,		FILTER_SYSEXIT },
{ PR_lstat,		FILTER_SYSEXIT },
{ PR_lstat64,		FILTER_SYSEXIT },
{ PR_newfstatat,	FILTER_SYSEXIT },
{ PR_oldlstat,		FILTER_SYSEXIT },
{ PR_oldstat,		FILTER_SYSEXIT },
{ PR_setfsgid,		FILTER_SYSEXIT },
{ PR_setfsgid32,	FILTER_SYSEXIT },
{ PR_setfsuid,		FILTER_SYSEXIT },
{ PR_setfsuid32,	FILTER_SYSEXIT },
{ PR_setgid,		FILTER_SYSEXIT },
{ PR_setgid32,		FILTER_SYSEXIT },
{ PR_setresgid,		FILTER_SYSEXIT },
{ PR_setresgid32,	FILTER_SYSEXIT },
{ PR_setresuid,		FILTER_SYSEXIT },
{ PR_setresuid32,	FILTER_SYSEXIT },
{ PR_setuid,		FILTER_SYSEXIT },
{ PR_setuid32,		FILTER_SYSEXIT },
{ PR_stat,		FILTER_SYSEXIT },
{ PR_stat64,		FILTER_SYSEXIT },
{ PR_statfs,		FILTER_SYSEXIT },
{ PR_statfs64,		FILTER_SYSEXIT },
