/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rootlesscontainers.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rootlesscontainers.pb-c.h"
void   rootlesscontainers__resource__init
                     (Rootlesscontainers__Resource         *message)
{
  static Rootlesscontainers__Resource init_value = ROOTLESSCONTAINERS__RESOURCE__INIT;
  *message = init_value;
}
size_t rootlesscontainers__resource__get_packed_size
                     (const Rootlesscontainers__Resource *message)
{
  assert(message->base.descriptor == &rootlesscontainers__resource__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rootlesscontainers__resource__pack
                     (const Rootlesscontainers__Resource *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rootlesscontainers__resource__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rootlesscontainers__resource__pack_to_buffer
                     (const Rootlesscontainers__Resource *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rootlesscontainers__resource__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rootlesscontainers__Resource *
       rootlesscontainers__resource__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rootlesscontainers__Resource *)
     protobuf_c_message_unpack (&rootlesscontainers__resource__descriptor,
                                allocator, len, data);
}
void   rootlesscontainers__resource__free_unpacked
                     (Rootlesscontainers__Resource *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &rootlesscontainers__resource__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rootlesscontainers__resource__field_descriptors[2] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Rootlesscontainers__Resource, has_uid),
    offsetof(Rootlesscontainers__Resource, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Rootlesscontainers__Resource, has_gid),
    offsetof(Rootlesscontainers__Resource, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rootlesscontainers__resource__field_indices_by_name[] = {
  1,   /* field[1] = gid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange rootlesscontainers__resource__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rootlesscontainers__resource__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rootlesscontainers.Resource",
  "Resource",
  "Rootlesscontainers__Resource",
  "rootlesscontainers",
  sizeof(Rootlesscontainers__Resource),
  2,
  rootlesscontainers__resource__field_descriptors,
  rootlesscontainers__resource__field_indices_by_name,
  1,  rootlesscontainers__resource__number_ranges,
  (ProtobufCMessageInit) rootlesscontainers__resource__init,
  NULL,NULL,NULL    /* reserved[123] */
};
