#undef __ARM_NR_breakpoint
#undef __ARM_NR_cacheflush
#undef __ARM_NR_set_tls
#undef __ARM_NR_usr26
#undef __ARM_NR_usr32
#undef __NR__llseek
#undef __NR__newselect
#undef __NR__sysctl
#undef __NR_accept4
#undef __NR_accept
#undef __NR_access
#undef __NR_acct
#undef __NR_add_key
#undef __NR_adjtimex
#undef __NR_afs_syscall
#undef __NR_alarm
#undef __NR_arch_prctl
#undef __NR_arm_fadvise64_64
#undef __NR_arm_sync_file_range
#undef __NR_bdflush
#undef __NR_bind
#undef __NR_break
#undef __NR_brk
#undef __NR_cacheflush
#undef __NR_capget
#undef __NR_capset
#undef __NR_chdir
#undef __NR_chmod
#undef __NR_chown32
#undef __NR_chown
#undef __NR_chroot
#undef __NR_clock_getres
#undef __NR_clock_gettime
#undef __NR_clock_nanosleep
#undef __NR_clock_settime
#undef __NR_clone
#undef __NR_close
#undef __NR_connect
#undef __NR_creat
#undef __NR_create_module
#undef __NR_delete_module
#undef __NR_dup2
#undef __NR_dup3
#undef __NR_dup
#undef __NR_epoll_create1
#undef __NR_epoll_create
#undef __NR_epoll_ctl
#undef __NR_epoll_ctl_old
#undef __NR_epoll_pwait
#undef __NR_epoll_wait
#undef __NR_epoll_wait_old
#undef __NR_eventfd2
#undef __NR_eventfd
#undef __NR_execve
#undef __NR_exit
#undef __NR_exit_group
#undef __NR_faccessat
#undef __NR_fadvise64
#undef __NR_fadvise64_64
#undef __NR_fallocate
#undef __NR_fanotify_init
#undef __NR_fanotify_mark
#undef __NR_fchdir
#undef __NR_fchmod
#undef __NR_fchmodat
#undef __NR_fchown32
#undef __NR_fchown
#undef __NR_fchownat
#undef __NR_fcntl64
#undef __NR_fcntl
#undef __NR_fdatasync
#undef __NR_fgetxattr
#undef __NR_flistxattr
#undef __NR_flock
#undef __NR_fork
#undef __NR_fremovexattr
#undef __NR_fsetxattr
#undef __NR_fstat64
#undef __NR_fstat
#undef __NR_fstatat64
#undef __NR_fstatfs64
#undef __NR_fstatfs
#undef __NR_fsync
#undef __NR_ftime
#undef __NR_ftruncate64
#undef __NR_ftruncate
#undef __NR_futex
#undef __NR_futimesat
#undef __NR_get_kernel_syms
#undef __NR_get_mempolicy
#undef __NR_get_robust_list
#undef __NR_get_thread_area
#undef __NR_getcpu
#undef __NR_getcwd
#undef __NR_getdents64
#undef __NR_getdents
#undef __NR_getegid32
#undef __NR_getegid
#undef __NR_geteuid32
#undef __NR_geteuid
#undef __NR_getgid32
#undef __NR_getgid
#undef __NR_getgroups32
#undef __NR_getgroups
#undef __NR_getitimer
#undef __NR_getpeername
#undef __NR_getpgid
#undef __NR_getpgrp
#undef __NR_getpid
#undef __NR_getpmsg
#undef __NR_getppid
#undef __NR_getpriority
#undef __NR_getresgid32
#undef __NR_getresgid
#undef __NR_getresuid32
#undef __NR_getresuid
#undef __NR_getrlimit
#undef __NR_getrusage
#undef __NR_getsid
#undef __NR_getsockname
#undef __NR_getsockopt
#undef __NR_gettid
#undef __NR_gettimeofday
#undef __NR_getuid32
#undef __NR_getuid
#undef __NR_getxattr
#undef __NR_gtty
#undef __NR_idle
#undef __NR_init_module
#undef __NR_inotify_add_watch
#undef __NR_inotify_init1
#undef __NR_inotify_init
#undef __NR_inotify_rm_watch
#undef __NR_io_cancel
#undef __NR_io_destroy
#undef __NR_io_getevents
#undef __NR_io_setup
#undef __NR_io_submit
#undef __NR_ioctl
#undef __NR_ioperm
#undef __NR_iopl
#undef __NR_ioprio_get
#undef __NR_ioprio_set
#undef __NR_ipc
#undef __NR_kexec_load
#undef __NR_keyctl
#undef __NR_kill
#undef __NR_lchown32
#undef __NR_lchown
#undef __NR_lgetxattr
#undef __NR_link
#undef __NR_linkat
#undef __NR_listen
#undef __NR_listxattr
#undef __NR_llistxattr
#undef __NR_lock
#undef __NR_lookup_dcookie
#undef __NR_lremovexattr
#undef __NR_lseek
#undef __NR_lsetxattr
#undef __NR_lstat64
#undef __NR_lstat
#undef __NR_madvise1 /* On i386 both values are equal. */
#undef __NR_madvise
#undef __NR_mbind
#undef __NR_migrate_pages
#undef __NR_mincore
#undef __NR_mkdir
#undef __NR_mkdirat
#undef __NR_mknod
#undef __NR_mknodat
#undef __NR_mlock
#undef __NR_mlockall
#undef __NR_mmap2
#undef __NR_mmap
#undef __NR_modify_ldt
#undef __NR_mount
#undef __NR_move_pages
#undef __NR_mprotect
#undef __NR_mpx
#undef __NR_mq_getsetattr
#undef __NR_mq_notify
#undef __NR_mq_open
#undef __NR_mq_timedreceive
#undef __NR_mq_timedsend
#undef __NR_mq_unlink
#undef __NR_mremap
#undef __NR_msgctl
#undef __NR_msgget
#undef __NR_msgrcv
#undef __NR_msgsnd
#undef __NR_msync
#undef __NR_munlock
#undef __NR_munlockall
#undef __NR_munmap
#undef __NR_nanosleep
#undef __NR_newfstatat
#undef __NR_nfsservctl
#undef __NR_nice
#undef __NR_oldfstat
#undef __NR_oldlstat
#undef __NR_oldolduname
#undef __NR_oldstat
#undef __NR_olduname
#undef __NR_open
#undef __NR_openat
#undef __NR_pause
#undef __NR_pciconfig_iobase
#undef __NR_pciconfig_read
#undef __NR_pciconfig_write
#undef __NR_perf_event_open
#undef __NR_personality
#undef __NR_pipe2
#undef __NR_pipe
#undef __NR_pivot_root
#undef __NR_poll
#undef __NR_ppoll
#undef __NR_prctl
#undef __NR_pread64
#undef __NR_preadv
#undef __NR_prlimit64
#undef __NR_prof
#undef __NR_profil
#undef __NR_pselect6
#undef __NR_ptrace
#undef __NR_putpmsg
#undef __NR_pwrite64
#undef __NR_pwritev
#undef __NR_query_module
#undef __NR_quotactl
#undef __NR_read
#undef __NR_readahead
#undef __NR_readdir
#undef __NR_readlink
#undef __NR_readlinkat
#undef __NR_readv
#undef __NR_reboot
#undef __NR_recv
#undef __NR_recvfrom
#undef __NR_recvmmsg
#undef __NR_recvmsg
#undef __NR_remap_file_pages
#undef __NR_removexattr
#undef __NR_rename
#undef __NR_renameat
#undef __NR_request_key
#undef __NR_restart_syscall
#undef __NR_rmdir
#undef __NR_rt_sigaction
#undef __NR_rt_sigpending
#undef __NR_rt_sigprocmask
#undef __NR_rt_sigqueueinfo
#undef __NR_rt_sigreturn
#undef __NR_rt_sigsuspend
#undef __NR_rt_sigtimedwait
#undef __NR_rt_tgsigqueueinfo
#undef __NR_sched_get_priority_max
#undef __NR_sched_get_priority_min
#undef __NR_sched_getaffinity
#undef __NR_sched_getparam
#undef __NR_sched_getscheduler
#undef __NR_sched_rr_get_interval
#undef __NR_sched_setaffinity
#undef __NR_sched_setparam
#undef __NR_sched_setscheduler
#undef __NR_sched_yield
#undef __NR_security
#undef __NR_select
#undef __NR_semctl
#undef __NR_semget
#undef __NR_semop
#undef __NR_semtimedop
#undef __NR_send
#undef __NR_sendfile64
#undef __NR_sendfile
#undef __NR_sendmsg
#undef __NR_sendto
#undef __NR_set_mempolicy
#undef __NR_set_robust_list
#undef __NR_set_thread_area
#undef __NR_set_tid_address
#undef __NR_setdomainname
#undef __NR_setfsgid32
#undef __NR_setfsgid
#undef __NR_setfsuid32
#undef __NR_setfsuid
#undef __NR_setgid32
#undef __NR_setgid
#undef __NR_setgroups32
#undef __NR_setgroups
#undef __NR_sethostname
#undef __NR_setitimer
#undef __NR_setpgid
#undef __NR_setpriority
#undef __NR_setregid32
#undef __NR_setregid
#undef __NR_setresgid32
#undef __NR_setresgid
#undef __NR_setresuid32
#undef __NR_setresuid
#undef __NR_setreuid32
#undef __NR_setreuid
#undef __NR_setrlimit
#undef __NR_setsid
#undef __NR_setsockopt
#undef __NR_settimeofday
#undef __NR_setuid32
#undef __NR_setuid
#undef __NR_setxattr
#undef __NR_sgetmask
#undef __NR_shmat
#undef __NR_shmctl
#undef __NR_shmdt
#undef __NR_shmget
#undef __NR_shutdown
#undef __NR_sigaction
#undef __NR_sigaltstack
#undef __NR_signal
#undef __NR_signalfd4
#undef __NR_signalfd
#undef __NR_sigpending
#undef __NR_sigprocmask
#undef __NR_sigreturn
#undef __NR_sigsuspend
#undef __NR_socket
#undef __NR_socketcall
#undef __NR_socketpair
#undef __NR_splice
#undef __NR_ssetmask
#undef __NR_stat64
#undef __NR_stat
#undef __NR_statfs64
#undef __NR_statfs
#undef __NR_stime
#undef __NR_streams1
#undef __NR_streams2
#undef __NR_stty
#undef __NR_swapoff
#undef __NR_swapon
#undef __NR_symlink
#undef __NR_symlinkat
#undef __NR_sync
#undef __NR_sync_file_range
#undef __NR_sysfs
#undef __NR_sysinfo
#undef __NR_syslog
#undef __NR_tee
#undef __NR_tgkill
#undef __NR_time
#undef __NR_timer_create
#undef __NR_timer_delete
#undef __NR_timer_getoverrun
#undef __NR_timer_gettime
#undef __NR_timer_settime
#undef __NR_timerfd_create
#undef __NR_timerfd_gettime
#undef __NR_timerfd_settime
#undef __NR_times
#undef __NR_tkill
#undef __NR_truncate64
#undef __NR_truncate
#undef __NR_tuxcall
#undef __NR_ugetrlimit
#undef __NR_ulimit
#undef __NR_umask
#undef __NR_umount2
#undef __NR_umount
#undef __NR_uname
#undef __NR_unlink
#undef __NR_unlinkat
#undef __NR_unshare
#undef __NR_uselib
#undef __NR_ustat
#undef __NR_utime
#undef __NR_utimensat
#undef __NR_utimes
#undef __NR_vfork
#undef __NR_vhangup
#undef __NR_vm86
#undef __NR_vm86old
#undef __NR_vmsplice
#undef __NR_vserver
#undef __NR_wait4
#undef __NR_waitid
#undef __NR_waitpid
#undef __NR_write
#undef __NR_writev
#undef __NR_sync_file_range2

